#!/usr/bin/env bash
#MISE description="Run a service container"
#MISE depends=["release:build"]
#USAGE flag "-p --port <port>" help="Host port to publish the container on" default="4000"

set -e

port="${usage_port:-4000}"

docker container run \
  --rm \
  --interactive \
  --tty \
  --publish "${port}:4000" \
  --name fire-starter-web \
  --env PHX_HOST=localhost \
  --env PORT=4000 \
  --env DATABASE_URL=ecto://postgres:postgres@host.docker.internal/fire_starter_dev \
  --env DATABASE_SSL=false \
  --env SECRET_KEY_BASE=XUHaTf95hc21ZGmnZZxestuSffWo2RRgTq+7l7d+1cygugxDsHeb3helkdU/oPnF \
  fire-starter-web bin/server
