#!/bin/sh
#MISE description="Set up the application for the first time after cloning, or reset it to its initial unused state"
#MISE depends=["bootstrap"]

set -e

docker compose up -d --wait

echo "==> Setting up project…"
# Ensure new env based config options are compiled
mix compile --force
mix setup

echo "==> The project is setup! 🚀 Is there demo data to load?"
