#!/bin/sh
#MISE description="Update the application to run for its current checkout"
#MISE depends=["bootstrap"]

set -e

docker compose up -d

echo "==> Updating db…"
# run all database migrations to ensure everything is up to date.
mix ecto.create
mix ecto.migrate
